name = "larry"
main = "./src/server.js"
compatibility_date="2023-05-18"


[vars]
DISCORD_WEBHOOK_URL="https://discord.com/api/webhooks/1419400644888101118/da_ZpbxeDSmPTM8-N1Av62mClm6ZyelMTpLF1C-y0scqQFRWbc5NNq53NPq8PEeinOgD"

[triggers]
crons = ["10 * * * *"]

[observability.logs]
enabled = true


[[kv_namespaces]]
binding = "PROMPT_CHANNELS"
id = "acb8e6a7e3f64fd4906301109695609b"

[[d1_databases]]
binding = "PROMPTS"
database_name = "prompts"
database_id = "d9fd1611-b804-4e99-8612-87627b1724bc"