name = "larry"
main = "./src/server.js"
compatibility_date="2023-05-18"


[vars]
DISCORD_WEBHOOK_URL="https://discord.com/api/webhooks/1419400644888101118/da_ZpbxeDSmPTM8-N1Av62mClm6ZyelMTpLF1C-y0scqQFRWbc5NNq53NPq8PEeinOgD"

[triggers]
crons = ["10 * * * *"]

[observability.logs]
enabled = true


[[kv_namespaces]]
binding = "PROMPT_CHANNELS"
id = "acb8e6a7e3f64fd4906301109695609b"

[[kv_namespaces]]
binding = "PERMISSION_LEVELS"
id = "61764b40fc854a74b8e9f8fbeab99101"

[[d1_databases]]
binding = "PROMPTS"
database_name = "prompts"
database_id = "d9fd1611-b804-4e99-8612-87627b1724bc"

[durable_objects]
bindings = [{
    name = "DEL_TIMEOUT",
    class_name = "DEL_TIMEOUT"
}]


[[migrations]]
tag = "v1"
new_sqlite_classes = ["DEL_TIMEOUT"]
